services:
  frontend:
    build: frontend
    ports:
      - "1002:80"
      - "2002:443"
    environment:
      - BACKEND_API_URL=http://192.168.4.101:1012/

  backend:
    build: backend
    ports:
      - "1012:80"
      - "2012:443"